// Generated by scripts/generate-backdrop-sprites.mjs - don't edit by hand.
// Fly-by sprite sheets: the GIF's frames side by side, each cropped to the
// character's box (x, y, w, h within the original GIF), shown for `delays` ms.
export interface BackdropSprite {
  sheet: string;
  x: number;
  y: number;
  w: number;
  h: number;
  delays: number[];
}

export const BACKDROP_SPRITES: Record<string, BackdropSprite> = {
  "https://cdn.sgxp.me/themes/ddz/eggmanboss.gif": {
    "sheet": "/themes/prerendered/ddz-eggmanboss.png",
    "x": 0,
    "y": 0,
    "w": 182,
    "h": 159,
    "delays": [
      50,
      50
    ]
  },
  "https://cdn.sgxp.me/themes/ddz/supersonic.gif": {
    "sheet": "/themes/prerendered/ddz-supersonic.png",
    "x": 0,
    "y": 0,
    "w": 37,
    "h": 34,
    "delays": [
      50,
      50,
      50,
      50
    ]
  },
  "https://cdn.sgxp.me/themes/hpz/sonic_run.gif": {
    "sheet": "/themes/prerendered/hpz-sonic_run.png",
    "x": 0,
    "y": 0,
    "w": 32,
    "h": 36,
    "delays": [
      60,
      60,
      60,
      60
    ]
  },
  "https://cdn.sgxp.me/themes/hpz/boss.gif": {
    "sheet": "/themes/prerendered/hpz-boss.png",
    "x": 0,
    "y": 0,
    "w": 330,
    "h": 228,
    "delays": [
      20,
      20
    ]
  },
  "https://cdn.sgxp.me/themes/ssz/mecha_01.gif": {
    "sheet": "/themes/prerendered/ssz-mecha_01.png",
    "x": 11932,
    "y": 11,
    "w": 64,
    "h": 54,
    "delays": [
      50,
      50,
      50
    ]
  },
  "https://cdn.sgxp.me/themes/ssz/mecha_02.gif": {
    "sheet": "/themes/prerendered/ssz-mecha_02.png",
    "x": 2,
    "y": 5,
    "w": 32,
    "h": 26,
    "delays": [
      50,
      50,
      50
    ]
  },
  "https://cdn.sgxp.me/themes/ssz/tornado_01.gif": {
    "sheet": "/themes/prerendered/ssz-tornado_01.png",
    "x": 11871,
    "y": 7,
    "w": 120,
    "h": 93,
    "delays": [
      20,
      20,
      20,
      20
    ]
  },
  "https://cdn.sgxp.me/themes/ssz/tornado_02.gif": {
    "sheet": "/themes/prerendered/ssz-tornado_02.png",
    "x": 9,
    "y": 0,
    "w": 60,
    "h": 48,
    "delays": [
      20,
      20
    ]
  }
};

// Animated GIFs replaced by a single still frame.
export const BACKDROP_STILLS: Record<string, string> = {
  "https://cdn.sgxp.me/themes/snow/snow_pattern.gif": "/themes/prerendered/snow-snow_pattern.png"
};
