// Image atlas for rendering a pixel font as images - see PixelText.svelte for why.
// GENERATED by scripts/generate-pixel-font-atlas.py from BN6FontTinyExt-fixed.ttf; don't
// edit by hand. Regenerate with that script (bumping --version), then upload the two PNGs
// to R2 at the URLs below (they're cached as immutable, so never overwrite an upload).
// Besides ASCII, includes the script's derived glyphs: '▾' / '▴' (nav dropdown carets).

export interface PixelGlyph {
  /** advance width in px (also the fill cell width) */
  w: number;
  /** x offset of this glyph's cell in the fill atlas */
  fx: number;
  /** x offset of this glyph's cell in the outline atlas (cells are w + 2 wide) */
  ox: number;
}

export interface PixelFont {
  /** white-on-transparent glyph shapes, used as a CSS mask so text takes the current color */
  fillUrl: string;
  /** glyphs dilated 1px in all 8 directions, baked in #1D1D20 (the old text-shadow outline) */
  outlineUrl: string;
  /** CSS font-size the atlas was drawn for - it's only pixel-exact at this size */
  size: number;
  /** px from the top of the line box to the baseline */
  ascent: number;
  lineHeight: number;
  glyphs: Record<string, PixelGlyph>;
}

export const navFont: PixelFont = {
  fillUrl: 'https://cdn.sgxp.me/img/fonts/nav-font-fill-v2.png',
  outlineUrl: 'https://cdn.sgxp.me/img/fonts/nav-font-outline-v2.png',
  size: 16,
  ascent: 12,
  lineHeight: 16,
  glyphs: {
    " ": { w: 5, fx: 0, ox: 0 },
    "!": { w: 4, fx: 5, ox: 7 },
    "\"": { w: 6, fx: 9, ox: 13 },
    "#": { w: 7, fx: 15, ox: 21 },
    "$": { w: 7, fx: 22, ox: 30 },
    "%": { w: 6, fx: 29, ox: 39 },
    "&": { w: 7, fx: 35, ox: 47 },
    "'": { w: 4, fx: 42, ox: 56 },
    "(": { w: 5, fx: 46, ox: 62 },
    ")": { w: 5, fx: 51, ox: 69 },
    "*": { w: 6, fx: 56, ox: 76 },
    "+": { w: 6, fx: 62, ox: 84 },
    ",": { w: 4, fx: 68, ox: 92 },
    "-": { w: 6, fx: 72, ox: 98 },
    ".": { w: 3, fx: 78, ox: 106 },
    "/": { w: 6, fx: 81, ox: 111 },
    "0": { w: 7, fx: 87, ox: 119 },
    "1": { w: 4, fx: 94, ox: 128 },
    "2": { w: 7, fx: 98, ox: 134 },
    "3": { w: 7, fx: 105, ox: 143 },
    "4": { w: 7, fx: 112, ox: 152 },
    "5": { w: 7, fx: 119, ox: 161 },
    "6": { w: 7, fx: 126, ox: 170 },
    "7": { w: 7, fx: 133, ox: 179 },
    "8": { w: 7, fx: 140, ox: 188 },
    "9": { w: 7, fx: 147, ox: 197 },
    ":": { w: 3, fx: 154, ox: 206 },
    ";": { w: 3, fx: 157, ox: 211 },
    "<": { w: 5, fx: 160, ox: 216 },
    "=": { w: 7, fx: 165, ox: 223 },
    ">": { w: 6, fx: 172, ox: 232 },
    "?": { w: 7, fx: 178, ox: 240 },
    "@": { w: 8, fx: 185, ox: 249 },
    "A": { w: 7, fx: 193, ox: 259 },
    "B": { w: 7, fx: 200, ox: 268 },
    "C": { w: 7, fx: 207, ox: 277 },
    "D": { w: 7, fx: 214, ox: 286 },
    "E": { w: 7, fx: 221, ox: 295 },
    "F": { w: 7, fx: 228, ox: 304 },
    "G": { w: 7, fx: 235, ox: 313 },
    "H": { w: 7, fx: 242, ox: 322 },
    "I": { w: 3, fx: 249, ox: 331 },
    "J": { w: 7, fx: 252, ox: 336 },
    "K": { w: 7, fx: 259, ox: 345 },
    "L": { w: 7, fx: 266, ox: 354 },
    "M": { w: 7, fx: 273, ox: 363 },
    "N": { w: 7, fx: 280, ox: 372 },
    "O": { w: 7, fx: 287, ox: 381 },
    "P": { w: 7, fx: 294, ox: 390 },
    "Q": { w: 7, fx: 301, ox: 399 },
    "R": { w: 7, fx: 308, ox: 408 },
    "S": { w: 7, fx: 315, ox: 417 },
    "T": { w: 7, fx: 322, ox: 426 },
    "U": { w: 7, fx: 329, ox: 435 },
    "V": { w: 7, fx: 336, ox: 444 },
    "W": { w: 7, fx: 343, ox: 453 },
    "X": { w: 7, fx: 350, ox: 462 },
    "Y": { w: 7, fx: 357, ox: 471 },
    "Z": { w: 7, fx: 364, ox: 480 },
    "[": { w: 4, fx: 371, ox: 489 },
    "\\": { w: 6, fx: 375, ox: 495 },
    "]": { w: 4, fx: 381, ox: 503 },
    "^": { w: 5, fx: 385, ox: 509 },
    "_": { w: 6, fx: 390, ox: 516 },
    "`": { w: 3, fx: 396, ox: 524 },
    "a": { w: 7, fx: 399, ox: 529 },
    "b": { w: 7, fx: 406, ox: 538 },
    "c": { w: 7, fx: 413, ox: 547 },
    "d": { w: 7, fx: 420, ox: 556 },
    "e": { w: 7, fx: 427, ox: 565 },
    "f": { w: 7, fx: 434, ox: 574 },
    "g": { w: 7, fx: 441, ox: 583 },
    "h": { w: 7, fx: 448, ox: 592 },
    "i": { w: 3, fx: 455, ox: 601 },
    "j": { w: 7, fx: 458, ox: 606 },
    "k": { w: 7, fx: 465, ox: 615 },
    "l": { w: 7, fx: 472, ox: 624 },
    "m": { w: 7, fx: 479, ox: 633 },
    "n": { w: 7, fx: 486, ox: 642 },
    "o": { w: 7, fx: 493, ox: 651 },
    "p": { w: 7, fx: 500, ox: 660 },
    "q": { w: 7, fx: 507, ox: 669 },
    "r": { w: 7, fx: 514, ox: 678 },
    "s": { w: 7, fx: 521, ox: 687 },
    "t": { w: 7, fx: 528, ox: 696 },
    "u": { w: 7, fx: 535, ox: 705 },
    "v": { w: 7, fx: 542, ox: 714 },
    "w": { w: 7, fx: 549, ox: 723 },
    "x": { w: 7, fx: 556, ox: 732 },
    "y": { w: 7, fx: 563, ox: 741 },
    "z": { w: 7, fx: 570, ox: 750 },
    "{": { w: 4, fx: 577, ox: 759 },
    "|": { w: 5, fx: 581, ox: 765 },
    "}": { w: 4, fx: 586, ox: 772 },
    "~": { w: 7, fx: 590, ox: 778 },
    "▾": { w: 5, fx: 597, ox: 787 },
    "▴": { w: 5, fx: 602, ox: 794 },
  },
};
