export default function GetRandomMsg() {
  let myMessageArray = [
    "Now you've reached a remarkable period in earth's history, known as the Cretaceous. It is a very different world. The Himalayas do not yet exist, and the Atlantic is only half as wide. There is no grass, only conifer forests and fern prairies. This is a world ruled by bans.",
    "WORDS UP THESE MIXED ARE",
    "Does what Nintendon't, SON!",
    "BEATERS OF DEAD HORSES! ALSO LIVE ONES! HORSE BURGERS! NEIGH!",
    "t!rank",
    "I found you! Faker!",
    "So we can remember Super Tails with wings",
    "Wait, a hidden t? Where?",
    "Where all good recolors come to rest",
    "ONLYFANS FOR SONIC FANS!",
    "Is that....hair gel?",
    "It’sa me! Sonic—oh...",
    "88 Miles Tails Prowler",
    "Tailsuigi, Numbar one!",
    "There's something about Amy",
    "Do these people ever sleep?",
    "Movie nights on Saturdays",
    "Take it to general",
    "WHAT IS AN ARCHIVE? A MISERABLE PILE OF PIXELS!",
    "Banned",
    " ｡ﾟ(ﾟ´Д｀ﾟ)ﾟ｡",
    "Feel old yet?",
    "(ノಠ益ಠ)ノ彡┻━┻ banned!!!",
    "Binned",
    "(☞ຈل͜ຈ)☞",
    "[insert creative slogan suggestion here]",
    "Oops I mean't to go to The Spriter's Resource",
    "Wait the Leaf Forest Zone is still around?",
    "You'll never believe who suggested this slogan.",
    "Coke or Pepsi?",
    "MGComics but worse",
    "MFZ gone? We gotchu",
    "Who burned the MFZ down this time?",
    "goodnight you guys, im going now. Bye",
    "MFZ? Best we can do is SGXP",
    "Like MFZ but with 1% of the drama",
    "What if we kissed in green hill zone .3.",
    "Got a Discord account? If so you outta join the Discord Server, No regrets",
    "Wait are you serious? He's in the Discord server? That guy is practically a God!",
    "Where Lost3DBlastFan got found",
    "NeW ShEeTs WhEN???",
    "Changing Fans, into Dans",
    "The Spriters Depot",
    "Sprites R' Us",
    "We spared no expense!",
    "You didn't say the magic word.",
    "We host Recolors Anonymous meetings every Wednesday",
    "It would make more sense if you read the user manual",
    "No good or evil, just Sonic Dans.",
    "Welcome To The SGXP! You're already banned.",
    "SGP: The X got Banned.",
    "SXP: The Gardow got Banned",
    "SGP: Xypter got Banned!?",
    "The carnyx was a wind instrument of the Iron Age Celts, used between c. 200 BC and c. AD 200. It was a type of bronze trumpet with an elongated S shape, held so that the long straight central portion was vertical and the short mouthpiece end section and the much wider bell were horizontal in opposed directions.",
    "Now you've reached a remarkable period in earth's history, known as the Cretaceous. It is a very different world. The Himalayas do not yet exist, and the Atlantic is only half as wide. There is no grass, only conifer forests and fern prairies. This is a world ruled by bans.",
    "A small family of spriters destined to shape the course of life in space for the next 160 million years. These are the last spriters, and this is where our story begins.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "Et tu Sonice?",
    "01001001 01100110 00100000 01111001 01101111 01110101 00100000 01100011 01100001 01101110 00100000 01110010 01100101 01100001 01100100 00100000 01110100 01101000 01101001 01110011 00101100 00100000 01111001 01101111 01110101 00100111 01110010 01100101 00100000 01100001 00100000 01101110 01100101 01110010 01100100",
    "We'll steal your sprites free of charge",
    "Alexa, play city escape.",
    "The forest has bloomed again, whether you like it or not",
    " ̿̿ ̿̿ ̿̿ ̿’̿’͇̿̿з= ( ▀ ͜͞ʖ▀) =ε/̵͇̿/’̿’̿ ̿ ̿̿ ̿̿ ̿̿",
    "Did you hear the MFZ came back? Hah! Got'm!",
    "This site is sponsored by, RAID SHADOW LEGENDS-",
    "But what does that X stand for?",
    "Recolor speedrun any %",
    "Fork around and find out",
    "Life    uh         finds a way.",
    "Look at all those Eggman's robots!",
    "All your base are belong to us",
    "[insert gif of everyone clapping from Evangelion]",
    "If the plural of mouse is mice, should the plural of spouse be spice?",
    "Hey that would be a pretty good slogan. Let me steal it.",
    "All work and no play makes Xypter a dull boy.",
    "Pixels alone moves the wheels of history.",
    "Now with 400% more giraffes!",
    "My OC could beat up your OC!",
    "First star on the left, then straight on ‘til morning!",
    "You can't just steal from SEGA. Steal from Disney too. Like my new OC Tick Tock the Croc.",
    "There is no joke.",
    "Haiku: The haiku master. Worked out this slogan for us. Truly we are blessed.",
    "Haiku: I’m so bleeping bad. At making haikus work out. Do you see what I...",
    "X marks the spot",
    "Sonic The Hedgehog on Xbox 360 and Playstation 3 is the best Sonic game!",
    "Mod's asleep, post Mario sprites",
    "Act -1",
    "Here I sit, Mouse in hand, I came to sprite, But instead got banned",
    "Limerick: We once went to an old server, full of members and many observers, but then it burned down, so we looked all around, for a new place where we could go further.",
    "Fetch me the mouse. I have to change the world through my Sonic fan-art.",
    "GET A LOAD OF THIS!",
    "Tonight at 10: Is your kid doing OC? The answer may shock you!",
    "Rolling around at the speed of sound, got places to go, got follow my rainbow",
    "We plan to get good slogans some day.",
    "Haiku: A server in space. Salvaging old sprite archives... What does the X mean?",
    "Haiku: A neat sprite I make. But not a very good one. Back to work I go",
    "Haiku: Here I sit, Mouse in hand. I came to sprite, but instead got banned.",
    "Fetch me the mouse. I have to change the world through my Sonic fan-art.",
    "Waiting for the inevitable ban to happen",
    "Tonight at 10: Is your kid doing OC? The answer may shock you!",
    "Where your opinion doesn't count!",
    "Dans Dans Revolution",
    "You get used to it",
    "The t is silent. And invisible.",
    "It's not personal, it's business.",
    "This slogan machine was a mistake",
    "XP MACHINE GO BRRRRR",
    "You either die a Sonic or live long enough to see yourself become the Scourge",
    "Rip & Tear",
    "<u>SOON</u>",
    "The happiest Sonic site on the web",
    "If you can read this, it’s already to late.",
    "It just ain't fair, G",
    "Selling dignity for $/£/€/¥. Inquire within.",
    "Pain; agony, even; suffering, if you will",
    "One does not simply enter The SGXP",
    "We should work towards world peace. Like giving everyone in the world an Upa cushion.",
    "Haiku: Slap some wings on tails, My biggest regret archived, What was I thinking...",
    "Es Gee Ex Pee",
    "Please tell me what to do.",
    "DON’T TELL ME WHAT TO DO!",
    "(▀̿Ĺ̯▀̿ ̿)",
    "¯_( ͡⟃ ͜ʖ ⟄)_/¯",
    "♪♬ ┗(＾0＾)┓",
    "ಥ_ಥ",
    "I nearly had to use 2% of my power.",
    "I want to see how many redesigns you can get through before this is over.",
    "Hello?........Hello?.........Hello?",
    "I think you should take a hike",
    "DO YOU SIT OR DO YOU STAND?!?!",
    "I am the one who dubs.",
    "I warned you bro",
    "<u>I am inevitable.</u>",
    "Please refer to the instruction manual for further questions.",
    "Backwards compatable with the Mystical Forest Zone!",
    "If you can see this refresh for a new slogan, I'm on my day off, mate.",
    "They're climbing in your windows, snatching your pixels up. Trying to rip them, so yall need to hide your pics, hide your sprites, and hide your tilesets cuz they're ripping everybody out here.",
    "Oh yeah? We'll make our own MFZ, with blackjack and hookers!",
    "Oh what tangled sprite we make, when stolen palettes we doth partake.",
    "You just lost the game",
    "42",
    "With mouse in hand I make a stroke, In bedroom dark where nigh is spoke, With bytes that form from screen lit bright, A pixel perfect, damn good sprite.",
    "He swore on the dubs, And thus sealed his fate, An unending cycle, Of sprites on his plate.",
    "Here I ponder, Paper in hand, I came to sit, But instead I stand.",
    "Memento mori.",
    "Succ to bone, bone to succ",
    "Your sprite doesnt deserve a spot in my folders! But it might make a good coaster for my drink!",
    "Failure to comply is unacceptable",
    "What are are these little tree sprouts doing here?",
    "I have run out of ideas for slogans",
    "We have new friends and old friends and even <u>insert name here!</u>",
    "Or your money back guaranteed",
    "We crack open a can of Sprite Sheets",
    "Rave? When?",
    "All your sprites R belong to us",
    "For spoons, we ri- wait, wrong website",
    "Promises of activity are purely theoretical and cannot be guarenteed.",
    "That's cool but can SGXP help me find my mom?",
    "We here, at SGXP, will not only find your mum, we will clone her so you will never lose her again",
    "Sprite archive go brrrrrr",
    "If you like SGXP, you'll love SGXP Premium!",
    "Home of the spriting freak, Gardow",
    "If you ain't a Sonic Dans, you getting the Sonic Bans",
    "Due to the recent Sonic sprite recession, all Sonic Dans transactions are final and non-refundable.",
    "Sonic Dans go BRRRRRR",
    "This is a velociraptor-free workplace, it has proudly been 2 days since the last incident (we miss you Xypter)",
    "I'll tell you what I want what I really really want",
    "Better than The Spriter’s Resource by 6!",
    "Humankind cannot gain anything without first giving something in return. To obtain, something of equal value must be lost. That is Alchemy's first law of Equivalent Exchange. In those days, we really believed that to be the world's one and only truth.",
    "I fart in your general direction",
    "SGXP: The Tank Engine?",
    "On this day, Blur swore to f-",
    "HE SAID THE THING",
    "Doing the thing",
    "All I wanted was dubs!",
    "Welcome to Hedgehogsville",
    "t!ratewaifu Kentucky Friend Gardow with Mayo",
    "The power of being British",
    "amogus",
    "SGXP means family. Family means nobody gets left behind or forgotten.",
    "When life gives you lemons, milk the system until the lemons in circulation over-saturate the market and cause a meltdown of the lemon economy.",
    "Proud sponsor of Pepsi",
    "If you want to blame anyone, Blame Blur",
    "You're welcome for this button, I accept chickens or goats for payment - Laguna"
  ];
  let randomMsg = myMessageArray[Math.floor(Math.random() * myMessageArray.length)];
  document.getElementById("message").innerHTML=randomMsg;
  return randomMsg;
}
GetRandomMsg()